name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Code
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build docker image
        run: docker build  -t kejetia-backend .
      - name: Push docker image
        run: docker push kejetia-backend:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from dockerhub 
        run: docker pull kejetia-backend:latest
      - name: Delete existing container
        run: docker rm -f kejetia-backend-container
      - name: run docker container
        run: docker run -d  -p 5000:5000 --name kejetia-backend-container  kejetia-backend



